// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUbD5ju-_mZrGNvPMv_E5wzJs99rkjF1g',
    appId: '1:617307420486:web:0414862e8365c482de5747',
    messagingSenderId: '617307420486',
    projectId: 'showroom-mobil-b887f',
    authDomain: 'showroom-mobil-b887f.firebaseapp.com',
    storageBucket: 'showroom-mobil-b887f.firebasestorage.app',
    measurementId: 'G-3H4MTDYC87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvzZDCXd2X6jfs4DhJKDKwhoq3-WyXYR0',
    appId: '1:617307420486:android:c1b6bd448e29628cde5747',
    messagingSenderId: '617307420486',
    projectId: 'showroom-mobil-b887f',
    storageBucket: 'showroom-mobil-b887f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYUdNdCdciR7tvoApiGhg2L1rhQ1-xEu4',
    appId: '1:617307420486:ios:77a3fdefd11b844ede5747',
    messagingSenderId: '617307420486',
    projectId: 'showroom-mobil-b887f',
    storageBucket: 'showroom-mobil-b887f.firebasestorage.app',
    androidClientId: '617307420486-om305id42svr4d8jq9c8j7654ns66uhf.apps.googleusercontent.com',
    iosClientId: '617307420486-pp4a5fgondq1j1u5nkoolre0acijmle3.apps.googleusercontent.com',
    iosBundleId: 'com.example.showroomMobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYUdNdCdciR7tvoApiGhg2L1rhQ1-xEu4',
    appId: '1:617307420486:ios:77a3fdefd11b844ede5747',
    messagingSenderId: '617307420486',
    projectId: 'showroom-mobil-b887f',
    storageBucket: 'showroom-mobil-b887f.firebasestorage.app',
    androidClientId: '617307420486-om305id42svr4d8jq9c8j7654ns66uhf.apps.googleusercontent.com',
    iosClientId: '617307420486-pp4a5fgondq1j1u5nkoolre0acijmle3.apps.googleusercontent.com',
    iosBundleId: 'com.example.showroomMobil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUbD5ju-_mZrGNvPMv_E5wzJs99rkjF1g',
    appId: '1:617307420486:web:4e29c83416ffa859de5747',
    messagingSenderId: '617307420486',
    projectId: 'showroom-mobil-b887f',
    authDomain: 'showroom-mobil-b887f.firebaseapp.com',
    storageBucket: 'showroom-mobil-b887f.firebasestorage.app',
    measurementId: 'G-WGLFS07997',
  );
}
