include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Tambahkan aturan linting sesuai kebutuhan
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true